# Copyright 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Cyril Koenig <cykoenig@iis.ee.ethz.ch>

DEVICES ?= spatz_cluster

CSRCS = main.c

CFLAGS   += -O3
#CFLAGS   += -v -debug -save-temps=obj

-include ../../common/default.mk
