#pragma once

#define QCTL_RESET_N_REG_OFFSET 0x4
#define QCTL_ISOLATE_REG_OFFSET 0x8
#define QCTL_TLB_WIDE_ENABLE_OFFSET 0x18
#define QCTL_TLB_NARROW_ENABLE_OFFSET 0x1c
#define QCTL_TLB_NARROW_REG_OFFSET 0x0800
#define QCTL_TLB_WIDE_REG_OFFSET 0x1000

#define QCTL_TLB_REG_STRIDE 0x20

#define QCTL_ISOLATE_NARROW_IN_BIT 0
#define QCTL_ISOLATE_NARROW_OUT_BIT 1
#define QCTL_ISOLATE_WIDE_IN_BIT 2
#define QCTL_ISOLATE_WIDE_OUT_BIT 3

#define SCTL_SCRATCH_0_REG_OFFSET 0x14
#define SCTL_SCRATCH_1_REG_OFFSET 0x18
#define SCTL_SCRATCH_2_REG_OFFSET 0x1c
#define SCTL_SCRATCH_3_REG_OFFSET 0x20
